### ISSUE TITLE
Failure on Windows

### ISSUE THREAD

**Issue by certik** [jkriege2/JKQtPlotter#35]
I am trying to get JKQtPlotter into Conda and I got it building on Linux and macOS, but I can't get it to build on Windows. Here is the PR:

https://github.com/conda-forge/staged-recipes/pull/10339

As you can see, I am really struggling to get it working on Windows. Any help would be appreciated.

**Comment by certik** [comment]
Here is the latest failure:

https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/29225954

```
...
  jkqtpstathistogram.cpp
  jkqtpstatkde.cpp
  jkqtpstatregression.cpp
  jkqtpstatpoly.cpp
  jkqtpstatgrouped.cpp
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: The command "setlocal [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: cd %SRC_DIR%\build\lib\jkqtcommon [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: C: [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: %BUILD_PREFIX%\Library\bin\cmake.exe -E __create_def C:/bld/jkqtplotter_1575148510775/work/build/lib/jkqtcommon/JKQTCommonSharedLib.dir/Release/exports.def C:/bld/jkqtplotter_1575148510775/work/build/lib/jkqtcommon/JKQTCommonSharedLib.dir/Release//objects.txt [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: :cmEnd [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: :cmErrorLevel [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: exit /b %1 [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: :cmDone [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code -1073741819. [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
Traceback (most recent call last):
  File ".ci_support\build_all.py", line 134, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support\build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File ".ci_support\build_all.py", line 124, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2344, in build_tree
    notest=notest,
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 1459, in build
    windows.build(m, build_file, stats=build_stats, provision_only=provision_only)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\windows.py", line 294, in build
    check_call_env(cmd, cwd=m.config.work_dir, stats=stats, rewrite_stdout_env=rewrite_env)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 398, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\utils.py", line 378, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
```

**Comment by jkriege2** [comment]
Hmmm dont really know whether I can tell (I don't know the combination of cake and vs all that well ... but maybe you can compare your buildcommands and vs versions to the ones used by my appveyor find ( see https://github.com/jkriege2/JKQtPlotter/blob/master/appveyor.yml )  ... I noticed some minor differences there ...

**Comment by jkriege2** [comment]
From a quick look 
1. I could not identify a call to vcvarsall.bat
2. I provided the generator to cmake explicitly
3.I don't combine build and install into one cmake command

Does any if thesehelp?

**Comment by certik** [comment]
Thanks. I tried a few things, and I separated the build from the install phase. It fails already during building somehow. It does not seem to be an issue in JKQtPlotter's CMake build system, at least not directly. But at the end of the day, I need it to install on Windows one way or another. If you can think of anything else, let me know. I'll keep trying also.

**Comment by certik** [comment]
I extracted the script that is being run from the error messages above:
```bat
setlocal 
cd %SRC_DIR%\build\lib\jkqtcommon
if %errorlevel% neq 0 goto :cmEnd
C:                                                              
if %errorlevel% neq 0 goto :cmEnd
%BUILD_PREFIX%\Library\bin\cmake.exe -E __create_def C:/bld/jkqtplotter_1575148510775/work/build/lib/jkqtcommon/JKQTCommonSharedLib.dir/Release/exports.def C:/bld/jkqtplotter_1575148510775/work/build/lib/jkqtcommon/JKQTCommonSharedLib.dir/Release//objects.txt [%SRC_DIR%\build\lib\jkqtcommon\JKQTCommonSharedLib.vcxproj]
if %errorlevel% neq 0 goto :cmEnd
:cmEnd                                                              
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel 
exit /b %1                                                              
:cmDone                                                              
if %errorlevel% neq 0 goto :VCEnd
```
And gives an error message `:VCEnd" exited with code -1073741819`.

**Comment by certik** [comment]
I think this is caused by this bug:

https://gitlab.kitware.com/cmake/cmake/issues/16282
https://github.com/conda/conda-build/issues/2850

**Comment by certik** [comment]
This was a nasty bug. I fixed it in https://github.com/conda-forge/staged-recipes/pull/10339/commits/bf808915e25ca48943f63ca85a9e81229cc803f1:
```diff
+set "CXXFLAGS= -MD"
```
